# Generated by Django 3.2.25 on 2024-12-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241216_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_table',
            name='POLICE_STATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_table',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.users_table'),
            preserve_default=False,
        ),
    ]
