# Generated by Django 3.2.25 on 2024-12-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20241216_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_table',
            name='POLICE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station'),
            preserve_default=False,
        ),
    ]
