# Generated by Django 3.2.25 on 2024-12-17 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_report_table_police'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_table',
            old_name='date',
            new_name='report_date',
        ),
        migrations.RenameField(
            model_name='report_table',
            old_name='time',
            new_name='report_time',
        ),
        migrations.RemoveField(
            model_name='report_table',
            name='POLICE',
        ),
        migrations.RemoveField(
            model_name='report_table',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='report_table',
            name='place',
        ),
        migrations.RemoveField(
            model_name='report_table',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report_table',
            name='visitorlogid',
        ),
        migrations.AddField(
            model_name='report_table',
            name='USER_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_table',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert_table',
            name='data',
            field=models.DateField(),
        ),
    ]
