# Generated by Django 3.2.25 on 2024-12-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20241217_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_table',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.users_table'),
            preserve_default=False,
        ),
    ]
