# Generated by Django 3.2.25 on 2024-12-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_camera_table_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_table',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='report_table',
            name='report_time',
        ),
        migrations.AddField(
            model_name='report_table',
            name='STATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report_table',
            name='images',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='report_table',
            name='report_date',
            field=models.DateTimeField(),
        ),
    ]
