# Generated by Django 3.2.25 on 2024-12-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20241217_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_table',
            name='action',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
