# Generated by Django 3.2.25 on 2024-12-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_report_table_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='complaint',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='complaint_table',
            name='replay',
            field=models.CharField(max_length=300),
        ),
    ]
