# Generated by Django 3.2.25 on 2024-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20241219_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
