# Generated by Django 3.2.25 on 2024-12-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_users_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='place',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
