# Generated by Django 3.2.25 on 2024-12-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station',
            name='langtitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='longtitude',
            field=models.FloatField(),
        ),
    ]
